env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:wc/recommended
  - plugin:lit/recommended
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  no-prototype-builtins: 0
  "@typescript-eslint/ban-types": 0
  "@typescript-eslint/explicit-function-return-type": 0
  "@typescript-eslint/explicit-module-boundary-types": 0
  "@typescript-eslint/no-explicit-any": "error"
  "@typescript-eslint/no-empty-function": 0
  "@typescript-eslint/no-non-null-assertion": 0
  "@typescript-eslint/no-unused-vars":
    - warn
    - argsIgnorePattern: "^_"

